---
- hosts: rancher
  sudo: True
  gather_facts: no
  tasks:
  - name: do stuff
    raw: apt-get update 
    raw: apt-get -y install python-minimal
  - name: install apt-transport-https
    apt: 
      name: apt-transport-https
      update_cache: yes
#  - name: upgrade
#    apt:
#      upgrade: yes
  - name: install software properties common
    apt: 
      name: software-properties-common
      update_cache: yes
  - apt_repository:
      repo: 'ppa:webupd8team/java'
      update_cache: yes
  - name: echo_auto
    raw: sh -c "echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections"
  - name: install java
    apt:
      name: oracle-java8-installer
      update_cache: yes
#    command: (apt -y update && apt install -y python-minimal)
#    apt:
#      name: python-minimal
#      update-cache: yes
#      force: yes
#  - name: other stuff
#    command: wget https://get.docker.io/gpg
#    command: apt-key add gpg
  - apt_key:
      keyserver: hkp://ha.pool.sks-keyservers.net:80
      id: 58118E89F3A912897C070ADBF76221572C52609D
  - name: intall Docker
    raw: sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - name: install Docker
    apt:
      name: lxc-docker
      update-cache: yes
      force: yes
#  - copy:
#      src: /home/evroon/DevOps/dockerfiles/acceptance/Dockerfile
#      dest: /home/ubuntu/Dockerfile
  - copy:
      src: /home/evroon/DevOps/dockerfiles/acceptance/id_rsa
      dest: /home/ubuntu/id_rsa
  - copy:
      src: /home/evroon/DevOps/dockerfiles/acceptance/id_rsa.pub
      dest: /home/ubuntu/id_rsa.pub
  - name: rancher server gogogo
#    raw: docker build -t="evroon/acc01" /home/ubuntu/
    raw: sudo docker run -ti -p 8080:8080 rancher/server
